### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by adieu** [mkrautz/objc#1]
When I set GOARCH to 386 and runs `go get github.com/mkrautz/objc` I got

```
# github.com/mkrautz/objc
../src/github.com/mkrautz/objc/typeinfo.go:64: undefined: typeInfoForType
../src/github.com/mkrautz/objc/typeinfo.go:73: undefined: typeInfoForType
../src/github.com/mkrautz/objc/typeinfo.go:77: undefined: typeInfoForType
class.go:148[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:116]: undefined: methodCallTarget
class.go:156[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:126]: undefined: methodCallTarget
class.go:163[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:135]: undefined: methodCallTarget
class.go:172[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:147]: cannot use object literal (type object) as type Class in return argument:
    object does not implement Class (missing SendMsg method)
class.go:177[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:153]: cannot use object literal (type object) as type Class in return argument:
    object does not implement Class (missing SendMsg method)
class.go:187[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:160]: cannot use object literal (type object) as type Class in return argument:
    object does not implement Class (missing SendMsg method)
class.go:212[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:194]: undefined: methodCallTarget
class.go:212[/var/folders/dl/1s6ftbmn4711tnq98gbm6c8m0000gn/T/go-build806992188/github.com/mkrautz/objc/_obj/class.cgo1.go:194]: too many errors
```

After looking into the source code, I found that there is only support for `GOARCH='amd64'`. I was trying to add 386 support but to find it's beyond my objc and c skills.

If it's possible, please add 32 bit support for this project. I was trying to use this project with another project which only support 32 bit. So I can't use the default 64 bit implementation.

**Comment by mkrautz** [comment]
It's not something that I had planned to do. Apple's Objective-C runtime on x86-64 is the so-called 'modern' runtime, where as i386 is still stuck on their legacy runtime.  I believe I have to support slightly different runtime APIs to support both -- but I'm not sure.

I will look at it, but I can't promise a timeframe.

**Comment by adieu** [comment]
Thanks a lot!

The other project I'm working with is CEF https://code.google.com/p/chromiumembedded/ which has only has 32 bit release for mac. I'm trying to build a 64 bit version from source but I'm not sure if it will work. My computer is pulling source code from chromium right now. There're quite a large amount of files there. I'll leave it there and go to sleep now. Hope there will be good result tomorrow.

**Comment by mkrautz** [comment]
Another thing: this package isn't very mature. It's very likely that it'll need some tweaking for your use case. What kind of Obj-C code are you planning on interfacing against?

**Comment by adieu** [comment]
I'm experimenting about writing desktop apps in Go with CEF. In order to display the CEF window, I need a thin wrapper for cocoa. That's what I wanted to use this package for. In my plan, I wanted to write as less objc as possible and leave most of the heavy lifting work to CEF where I could write html and js.

I've compiled CEF from source. But the default setting is till 32 bit. Maybe I should go to CEF mailing list asking for some help.

**Comment by mkrautz** [comment]
I don't believe there are 32-bit Chrom{e,ium} builds for OS X, so it makes sense that there'd be no CEF builds either.

I'll see what I can do to bring this package up to speed for GOARCH=386.

In the meantime, I should note that it should also be possible to write Objective-C directiy via the cgo API, if you tell the compiler that your code is indeed ObjC. For example like this:

#cgo CFLAGS -x objective-c

**Comment by adieu** [comment]
I tried your method writing objc via cgo but it doesn't work.

Found this issue https://code.google.com/p/go/issues/detail?id=1781 on google code. Will try again after it got resolved.

**Comment by mkrautz** [comment]
A little update:

I've added rudimentary 386 support to my variadic package which the objc package depends on for calling through to objc_msgSend: https://github.com/mkrautz/variadic

I still need to fix a few things in it, but integer arguments work and floating point and integer return values work.

**Comment by adieu** [comment]
That was quick. I'll test the 32 bit code when everything is ready.

**Comment by mkrautz** [comment]
I have landed another milestone piece to the repo: https://github.com/mkrautz/objc/commit/be329cd683dffea48b31b1e083c16114aafd5254

It pretty much seems to work, but it's missing proper struct handling. So, things like NSRect, NSPoint and NSSize are not correctly passed to functions. (For example, the NSWindow test in AppKit hangs).

I will look ito it as soon as I have time.

BTW: The main Go repo now has support for using the host linker instead of the 6l linker to link cgo binaries. It's very possible that your issue with linking ObjC is gone.

**Comment by adieu** [comment]
Great news!

I have gone with the road to put all objc related code in an separate C library and link it with the Go code with my project. I've put the initial version on github( https://github.com/adieu/go-cef ) but it's in a very early stage and I have to write some documentation explaining how to use my code.

I'll test the objc project when I have some free time. If everything goes well, I could remove the external library for objc and write all code in Go. That would be perfect.

I'll test the tip version of Go too. But that would be my second choice.

**Comment by mkrautz** [comment]
Structs are now handled correctly with f09aeb339fc17bfb7df7dfefe99c424e306528c7 and https://github.com/mkrautz/objc/commit/07ef1c97073160b2699ecd5138c934a3828b684e landed.

I think I'll close this now, as (as far as I know) there is feature parity between both the 386 and amd64 versions of the package now.

But please be aware that it's still highly experimental, and I haven't written any real apps in it yet. :-)

If you, in the future, find discrepancies or bugs in general, please create new tickets for them.

Thanks!
